### PR TITLE
Patch deps and move to typescript

### PR DESCRIPTION
**Pull request by nebulatgs**
ncc was ancient also yarn is nice

### CODE REVIEW

**Review by CompeyDev — APPROVED** [review]

**Review by CompeyDev — APPROVED** [review]

**Review by CompeyDev — APPROVED** [review]

**Comment by clima-dev** [comment]
JUST EMRGE IT OMGGGGGGGGGGG

**Comment by CompeyDev** [comment]
Commit 81f2f681dd599d723a43c2adbd1e28693cb0dbd4 merges it into the branch.

**Comment by Milo123459** [comment]
Do you.. not know how to use GitHub?

**Comment by CompeyDev** [comment]
> Do you.. not know how to use GitHub?

I don't want to merge into main because it could end up breaking the whole thing, keeping it on another branch for now.

**Review by CompeyDev — COMMENTED** [review]
Canceled move to typescript.

**Pull request closed without merging**
