### PR TITLE
Update libv2.js

### PR DESCRIPTION
**Pull request by asmtilde**

### CODE REVIEW

**Comment by CompeyDev** [comment]
Hi! I am unsure as to what the point of this PR is, could you explain it further to me? Thanks for your contribution :)

**Comment by asmtilde** [comment]
Fix for extra spacing and words

**Comment by CompeyDev** [comment]
Nah, it doesn't seem necessary. Further flight doesn't have it's own system. It just uses the same system that node uses.

**Review by CompeyDev — COMMENTED** [review]
Unneeded.

**Pull request closed without merging**
